### ISSUE TITLE
failed start on win 8.1

### ISSUE THREAD

**Issue by Alexmakes** [vishwenga/Smart-Audio-Book-Player#1]
fails to start on the latest build of windows 8.1 
![2018-01-20_16-55-57](https://user-images.githubusercontent.com/9121416/35185880-e7387ee0-fe02-11e7-8ca3-c5e4ac2280cd.gif)
prob due to no windows media player installed.
loads fine of latest build on windows 10

**Comment by 00000vish** [comment]
Windows 8 will reach end of Mainstream Support on January 9, 2018. 

Not much i can do  :(
